/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;


import Formularios.frm_principal;
import clases.consultas;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class jpf_agenda extends javax.swing.JPanel {
private consultas co =new consultas();
String fecha2;
    /**
     * Creates new form jpf_agenda
     */
public void limpiar_hora(){
this.cb_hora.removeAllItems();
        this.cb_hora.setEnabled(false);

}
    public jpf_agenda() {
        initComponents();
        this.chk_no.setEnabled(false);
        this.chk_si.setEnabled(false);
        cb_hora.removeAllItems();
        cb_profesional.removeAllItems();
        co.obtener_profesionales(cb_profesional);
        co.obtener_tipo_hora(cb_tipo_hora);
        this.txt_rut_paciente.setEditable(false);
        this.cb_hora.setEditable(false);
        this.bt_agendar.setEnabled(false);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_agendar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdc_calendario = new com.toedter.calendar.JDateChooser();
        cb_profesional = new javax.swing.JComboBox<>();
        cb_tipo_hora = new javax.swing.JComboBox<>();
        cb_hora = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        chk_si = new javax.swing.JCheckBox();
        chk_no = new javax.swing.JCheckBox();
        txt_rut_paciente = new javax.swing.JFormattedTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Profesional:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Dia:");

        jLabel4.setText("Hora:");

        jLabel5.setText("Rut Paciente:");

        bt_agendar.setText("Agendar");
        bt_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agendarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agenda");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/009.png"))); // NOI18N

        cb_profesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_profesionalActionPerformed(evt);
            }
        });

        cb_tipo_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_horaActionPerformed(evt);
            }
        });

        cb_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_horaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Hora cirugia:");

        chk_si.setText("Si");
        chk_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_siActionPerformed(evt);
            }
        });

        chk_no.setText("No");
        chk_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(bt_agendar)
                        .addGap(200, 238, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rut_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(220, 220, 220)
                                .addComponent(jButton1))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chk_si)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_no))
                                    .addComponent(cb_profesional, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdc_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cb_tipo_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 74, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_rut_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_profesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_tipo_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chk_si)
                    .addComponent(chk_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(bt_agendar)
                .addContainerGap())
        );

        jdc_calendario.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent e) {
                //Aquí agregaremos la funcionalidad que queremos
                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                limpiar_hora();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agendarActionPerformed
       try{
        Date  fecha=jdc_calendario.getDate();
        DateFormat f=new SimpleDateFormat("dd-MM-yyyy");
        this.fecha2=f.format(fecha);
    } catch (Exception e) {
}
       
        co.setRut_profesional(cb_profesional.getItemAt(cb_profesional.getSelectedIndex()).getRut_profesional());
       co.setRut_paciente(this.txt_rut_paciente.getText());
       co.guardar_cita(this.txt_rut_paciente.getText(),cb_profesional.getItemAt(cb_profesional.getSelectedIndex()).getRut_profesional()
                        ,cb_hora.getItemAt(cb_hora.getSelectedIndex()).getHor_id() , 
                        fecha2,cb_tipo_hora.getItemAt(cb_tipo_hora.getSelectedIndex()).getTipo_hora_id() );

        new clases.CambiaPanel(frm_principal.jp_box,new jpf_buscar_paciente());
            
        
    }//GEN-LAST:event_bt_agendarActionPerformed

    private void cb_tipo_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_horaActionPerformed
        limpiar_hora();
        
    }//GEN-LAST:event_cb_tipo_horaActionPerformed

    private void cb_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_horaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.cb_hora.removeAllItems();
        
        try{
            Date  fecha=jdc_calendario.getDate();
            DateFormat f=new SimpleDateFormat("dd-MM-yyyy");
            this.fecha2=f.format(fecha);
        }catch (NullPointerException e) {
            
            JOptionPane.showMessageDialog(this, "Debes ingresar una fecha","Error", JOptionPane.ERROR_MESSAGE);
        
        }
        if(this.fecha2 != null){
        co.setRut_profesional(cb_profesional.getItemAt(cb_profesional.getSelectedIndex()).getRut_profesional());
        co.setTipo_hora_id(cb_tipo_hora.getItemAt(cb_tipo_hora.getSelectedIndex()).getTipo_hora_id());
        co.setFecha_cita(fecha2);
        co.obtener_horadisponible(cb_hora);
        this.cb_hora.setEnabled(true);
        this.bt_agendar.setEnabled(true);
        }
        
        
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_profesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_profesionalActionPerformed
        limpiar_hora();
    }//GEN-LAST:event_cb_profesionalActionPerformed

    private void chk_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_siActionPerformed
        this.chk_si.setSelected(true);
        this.chk_no.setSelected(false);
    }//GEN-LAST:event_chk_siActionPerformed

    private void chk_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_noActionPerformed
        this.chk_no.setSelected(true);
        this.chk_si.setSelected(false);
    }//GEN-LAST:event_chk_noActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agendar;
    private javax.swing.JComboBox<consultas> cb_hora;
    private javax.swing.JComboBox<consultas> cb_profesional;
    private javax.swing.JComboBox<consultas> cb_tipo_hora;
    private javax.swing.JCheckBox chk_no;
    private javax.swing.JCheckBox chk_si;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.calendar.JDateChooser jdc_calendario;
    public static javax.swing.JFormattedTextField txt_rut_paciente;
    // End of variables declaration//GEN-END:variables
}
