/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Paneles.jpf_buscar_paciente;
import Paneles.jpf_bloqueos;
import Paneles.jpf_citaciones;
import java.awt.Color;
import clases.CambiaPanel;

/**
 *
 * @author Family
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
   int boton; 
public void botones(){
        
        this.bt_pacientes.setColorNormal(new Color(204,204,255));
        this.bt_pacientes.setColorHover(new Color(102,102,255));
        this.bt_pacientes.setColorPressed(new Color(204,204,255));
    
        this.bt_citaciones.setColorNormal(new Color(204,204,255));
        this.bt_citaciones.setColorHover(new Color(102,102,255));
        this.bt_citaciones.setColorPressed(new Color(204,204,255));
        
        this.bt_bloqueos.setColorNormal(new Color(204,204,255));
        this.bt_bloqueos.setColorHover(new Color(102,102,255));
        this.bt_bloqueos.setColorPressed(new Color(204,204,255));
        
       switch (boton) {
           case 1:
               this.bt_pacientes.setColorNormal(new Color(255,255,255));
               this.bt_pacientes.setColorHover(new Color(102,102,255));
               this.bt_pacientes.setColorPressed(new Color(255,255,255));
               new CambiaPanel(jp_box, new jpf_buscar_paciente());
               break;
           case 2:
               this.bt_citaciones.setColorNormal(new Color(255,255,255));
               this.bt_citaciones.setColorHover(new Color(102,102,255));
               this.bt_citaciones.setColorPressed(new Color(255,255,255));
               new CambiaPanel(jp_box, new jpf_citaciones());
               break;
           case 3:
               this.bt_bloqueos.setColorNormal(new Color(255,255,255));
               this.bt_bloqueos.setColorHover(new Color(102,102,255));
               this.bt_bloqueos.setColorPressed(new Color(255,255,255));
               new CambiaPanel(jp_box, new jpf_bloqueos());
               break;
           default:
               break;
       }

}
    
    public frm_principal() {
        initComponents();
        //setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_nombre_usuario = new javax.swing.JLabel();
        jp_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_citaciones = new clases.RSButtonMetro();
        bt_reportes = new clases.RSButtonMetro();
        bt_bloqueos = new clases.RSButtonMetro();
        bt_pacientes = new clases.RSButtonMetro();
        jp_box = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombre_usuario.setText("nombre usuario");
        jPanel2.add(lbl_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jp_menu.setBackground(new java.awt.Color(204, 204, 255));
        jp_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Consulta Medica");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jp_menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        bt_citaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/048.png"))); // NOI18N
        bt_citaciones.setText("Citaciones");
        bt_citaciones.setColorNormal(new java.awt.Color(204, 204, 255));
        bt_citaciones.setColorPressed(new java.awt.Color(153, 153, 255));
        bt_citaciones.setColorTextHover(new java.awt.Color(51, 51, 51));
        bt_citaciones.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bt_citaciones.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bt_citaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_citaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_citacionesMousePressed(evt);
            }
        });
        bt_citaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_citacionesActionPerformed(evt);
            }
        });
        jp_menu.add(bt_citaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 190, 44));

        bt_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/048.png"))); // NOI18N
        bt_reportes.setText("Reportes");
        bt_reportes.setColorNormal(new java.awt.Color(204, 204, 255));
        bt_reportes.setColorPressed(new java.awt.Color(153, 153, 255));
        bt_reportes.setColorTextHover(new java.awt.Color(51, 51, 51));
        bt_reportes.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bt_reportes.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bt_reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportesActionPerformed(evt);
            }
        });
        jp_menu.add(bt_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 214, 190, 44));

        bt_bloqueos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/048.png"))); // NOI18N
        bt_bloqueos.setText("Bloqueos");
        bt_bloqueos.setColorNormal(new java.awt.Color(204, 204, 255));
        bt_bloqueos.setColorPressed(new java.awt.Color(153, 153, 255));
        bt_bloqueos.setColorTextHover(new java.awt.Color(51, 51, 51));
        bt_bloqueos.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bt_bloqueos.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bt_bloqueos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_bloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_bloqueosMousePressed(evt);
            }
        });
        bt_bloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bloqueosActionPerformed(evt);
            }
        });
        jp_menu.add(bt_bloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 164, 190, 44));

        bt_pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/048.png"))); // NOI18N
        bt_pacientes.setText("Pacientes");
        bt_pacientes.setColorNormal(new java.awt.Color(204, 204, 255));
        bt_pacientes.setColorPressed(new java.awt.Color(153, 153, 255));
        bt_pacientes.setColorTextHover(new java.awt.Color(51, 51, 51));
        bt_pacientes.setColorTextNormal(new java.awt.Color(51, 51, 51));
        bt_pacientes.setColorTextPressed(new java.awt.Color(51, 51, 51));
        bt_pacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bt_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pacientesActionPerformed(evt);
            }
        });
        jp_menu.add(bt_pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 190, 41));

        jPanel1.add(jp_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 540));

        jp_box.setBackground(new java.awt.Color(255, 255, 255));
        jp_box.setLayout(new javax.swing.BoxLayout(jp_box, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jp_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 810, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_citacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_citacionesActionPerformed
        this.boton=2;
        botones();
       
    }//GEN-LAST:event_bt_citacionesActionPerformed

    private void bt_bloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bloqueosActionPerformed
       this.boton=3;
        botones();
        
    }//GEN-LAST:event_bt_bloqueosActionPerformed

    private void bt_citacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_citacionesMousePressed
        
    }//GEN-LAST:event_bt_citacionesMousePressed

    private void bt_bloqueosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bloqueosMousePressed
        
    }//GEN-LAST:event_bt_bloqueosMousePressed

    private void bt_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pacientesActionPerformed
      
        this.boton=1;
        botones();
        
    }//GEN-LAST:event_bt_pacientesActionPerformed

    private void bt_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportesActionPerformed
        
    }//GEN-LAST:event_bt_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private clases.RSButtonMetro bt_bloqueos;
    private clases.RSButtonMetro bt_citaciones;
    private clases.RSButtonMetro bt_pacientes;
    private clases.RSButtonMetro bt_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jp_box;
    private javax.swing.JPanel jp_menu;
    public javax.swing.JLabel lbl_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
