/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Family
 */
public class frm_inicio extends javax.swing.JFrame {

    /**
     * Creates new form frm_inicio
     */
    public frm_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_agen_agregar = new javax.swing.JButton();
        bt_agen_eliminar = new javax.swing.JButton();
        bt_agen_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_agen_agregar.setText("Agregar");
        bt_agen_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agen_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_agen_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        bt_agen_eliminar.setText("Eliminar");
        bt_agen_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agen_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_agen_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        bt_agen_modificar.setText("Modificar");
        jPanel1.add(bt_agen_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agen_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agen_eliminarActionPerformed
      frm_agregar_agenda f_ag_ag =new frm_agregar_agenda();
        f_ag_ag.setTipo("2");
        System.out.println(f_ag_ag.getTipo());
        f_ag_ag.calendario.setEnabled(false);
        f_ag_ag.cbx_hora.setEnabled(false);
        f_ag_ag.cbx_personal.setEnabled(false);
        f_ag_ag.bt_agendar.setEnabled(false);
        f_ag_ag.setVisible(true);
        
    }//GEN-LAST:event_bt_agen_eliminarActionPerformed

    private void bt_agen_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agen_agregarActionPerformed
        frm_agregar_agenda f_ag_ag =new frm_agregar_agenda();
        f_ag_ag.setTipo("1");
        f_ag_ag.formato_fecha();
        f_ag_ag.setVisible(true);
        
    }//GEN-LAST:event_bt_agen_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agen_agregar;
    private javax.swing.JButton bt_agen_eliminar;
    private javax.swing.JButton bt_agen_modificar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
